export const GET_BRANDS_LIST = "GET_BRANDS_LIST";
export const GET_BRAND_PRODUCTS = "GET_BRAND_PRODUCTS";
export const GET_CATEGORIES_OF_BRAND_PRODUCTS =
  "GET_CATEGORIES_OF_BRAND_PRODUCTS";
export const CLEAR_BRAND_PRODUCTS = "CLEAR_BRAND_PRODUCTS";
export const GET_CATEGORIES_LIST = "GET_CATEGORIES_LIST";
export const GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS";
export const GET_BRANDS_OF_CATEGORY_PRODUCTS =
  "GET_BRANDS_OF_CATEGORY_PRODUCTS";
export const CLEAR_CATEGORY_PRODUCTS = "CLEAR_CATEGORY_PRODUCTS";
export const GET_FEATURED_PRODUCTS = "GET_FEATURED_PRODUCTS";
export const GET_GENDER_PRODUCTS = "GET_GENDER_PRODUCTS";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_GENDER_BRANDS_CATEGORIES = "GET_GENDER_BRANDS_CATEGORIES";
export const CLEAR_PRODUCT_DETAIL = "CLEAR_PRODUCT_DETAIL";
export const UPDATE_PRODUCT_STATUS = "UPDATE_PRODUCT_STATUS";
export const GET_FEATURED_BRANDS_CATEGORIES = "GET_FEATURED_BRANDS_CATEGORIES";
export const SUBSCRIBE_PRODUCT = "SUBSCRIBE_PRODUCT";
