# Generated by Django 3.1 on 2020-09-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together=set(),
        ),
    ]
